//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simcard
    {
        public int SimcardID { get; set; }
        public Nullable<int> Number { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CorporateID { get; set; }
    }
}
